---
services:
  backend:
    build:
      target: development
    ports:
      - "8000:8000"
      - "5678:5678"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: pyproject.toml
