---
services:
  backend:
    build:
      target: development
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:5678:5678"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: pyproject.toml
  db:
    ports:
      - "127.0.0.1:5432:5432"
