services:
  caddy:
    image: caddy:2.11.2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./caddy:/etc/caddy:ro
      - static:/srv/static
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    volumes:
      - static:/app/src/staticfiles

  db:
    image: postgres:18.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/18/data

volumes:
  static:
  db_data:
