# Generated by Django 5.1 on 2024-08-25 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('exercise_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practiced_on', models.DateField(auto_now_add=True)),
                ('tempo', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('', 'Not Rated'), ('very_easy', 'Very Easy'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], default='', max_length=10)),
                ('relaxation_level', models.CharField(choices=[('', 'Not Recorded'), ('very_tense', 'Very Tense'), ('tense', 'Tense'), ('neutral', 'Neutral'), ('relaxed', 'Relaxed'), ('very_relaxed', 'Very Relaxed')], default='', max_length=12)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_logs', to='book_tracker.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='book_tracker.book')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='book_tracker.section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('book', 'order'), name='unique_section_order'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('section', 'exercise_number'), name='unique_exercise_number'),
        ),
    ]
