# Generated by Django 6.0.4 on 2026-04-16 10:03

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("page_count", models.PositiveIntegerField()),
                ("authors", models.ManyToManyField(related_name="books", to="book_tracker.author")),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                ("book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="book_tracker.book")),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("exercise_number", models.PositiveSmallIntegerField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="exercises", to="book_tracker.section")),
                ("tags", models.ManyToManyField(blank=True, related_name="exercises", to="book_tracker.tag")),
            ],
        ),
        migrations.CreateModel(
            name="PracticeLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("practiced_on", models.DateField(db_index=True, default=datetime.date.today)),
                ("tempo", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(choices=[(0, "Not Rated"), (1, "Very Easy"), (2, "Easy"), (3, "Medium"), (4, "Hard"), (5, "Very Hard")], default=0),
                ),
                (
                    "relaxation_level",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Not Recorded"), (1, "Very Tense"), (2, "Tense"), (3, "Neutral"), (4, "Relaxed"), (5, "Very Relaxed")], default=0
                    ),
                ),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="practice_logs", to="book_tracker.exercise")),
            ],
            options={
                "indexes": [models.Index(fields=["exercise", "practiced_on"], name="idx_practice_exercise_date")],
            },
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(fields=("book", "order"), name="unique_section_order"),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(fields=("section", "exercise_number"), name="unique_exercise_number"),
        ),
    ]
