# Generated by Django 5.1 on 2024-08-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="books", to="book_tracker.author"
            ),
        ),
    ]
