# Generated by Django 6.0.4 on 2026-04-20 09:52

from django.db import migrations, models


def populate_identifier_and_description(apps, schema_editor):
    """Copy exercise_number → identifier and title → description for existing rows."""
    Exercise = apps.get_model("book_tracker", "Exercise")
    for exercise in Exercise.objects.all():
        exercise.identifier = str(exercise.exercise_number)
        exercise.description = exercise.title
        exercise.save(update_fields=["identifier", "description"])


class Migration(migrations.Migration):

    dependencies = [
        ('book_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercise',
            name='unique_exercise_number',
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RunPython(
            populate_identifier_and_description,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('identifier', ''), _negated=True), fields=('section', 'identifier'), name='unique_exercise_identifier'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), ('identifier', ''), _negated=True), name='exercise_identifier_or_description_required'),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_number',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
    ]
