# Generated by Django 6.0.4 on 2026-04-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tracker', '0002_exercise_identifier_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='notation_image',
            field=models.ImageField(blank=True, upload_to='notation/images/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='notation_musicxml',
            field=models.FileField(blank=True, upload_to='notation/musicxml/'),
        ),
    ]
