# Generated by Django 5.1 on 2024-08-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_tracker", "0002_author_book_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="page_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="exercises", to="book_tracker.tag"
            ),
        ),
    ]
