# Generated by Django 5.1 on 2024-09-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_tracker", "0003_tag_exercise_page_number_exercise_tags"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name"), name="unique_name"
            ),
        ),
    ]
