# Generated by Django 6.0.4 on 2026-04-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_tracker', '0003_exercise_notation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='notation_musicxml',
        ),
    ]
