# Generated by Django 5.1 on 2024-09-01 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_tracker", "0004_author_unique_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
