# Generated by Django 5.1 on 2024-09-01 01:54

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_tracker", "0005_remove_exercise_tags_delete_tag"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
