from django.urls import path

from book_tracker import htmx_crud_views, views

urlpatterns = [
    path("authors/", views.author_list, name="author-list"),
    path("authors/create/", views.author_create, name="author-create"),
    path("authors/<str:pk>/", views.author_row, name="author-row"),
    path("authors/table-body/", views.author_table_body, name="author-table-body"),
    path("authors/<str:pk>/edit/", views.author_edit, name="author-edit"),
    path("authors/<str:pk>/update/", views.author_update, name="author-update"),
    path("authors/<str:pk>/delete/", views.author_delete, name="author-delete"),
    path("authors/<str:pk>/delete/confirm/", views.author_confirm_delete, name="author-confirm-delete"),
    path("tags/", htmx_crud_views.tag_list, name="tag-list"),
    path("tags/create/", htmx_crud_views.tag_create, name="tag-create"),
    path("tags/<str:pk>/", htmx_crud_views.tag_row, name="tag-row"),
    path("tags/<str:pk>/edit/", htmx_crud_views.tag_edit, name="tag-edit"),
    path("tags/<str:pk>/update/", htmx_crud_views.tag_update, name="tag-update"),
    path("tags/<str:pk>/delete/", htmx_crud_views.tag_delete, name="tag-delete"),
    path("tags/<str:pk>/delete/confirm/", htmx_crud_views.tag_confirm_delete, name="tag-confirm-delete"),
    path("books/", htmx_crud_views.book_list, name="book-list"),
    path("books/create/", htmx_crud_views.book_create, name="book-create"),
    path("books/<str:pk>/", htmx_crud_views.book_row, name="book-row"),
    path("books/<str:pk>/edit/", htmx_crud_views.book_edit, name="book-edit"),
    path("books/<str:pk>/update/", htmx_crud_views.book_update, name="book-update"),
    path("books/<str:pk>/delete/", htmx_crud_views.book_delete, name="book-delete"),
    path("books/<str:pk>/delete/confirm/", htmx_crud_views.book_confirm_delete, name="book-confirm-delete"),
    path("sections/", htmx_crud_views.section_list, name="section-list"),
    path("sections/bulk-create/", htmx_crud_views.section_bulk_create, name="section-bulk-create"),
    path("sections/form-row/", htmx_crud_views.section_form_row, name="section-form-row"),
    path("sections/<str:pk>/", htmx_crud_views.section_row, name="section-row"),
    path("sections/<str:pk>/edit/", htmx_crud_views.section_edit, name="section-edit"),
    path("sections/<str:pk>/update/", htmx_crud_views.section_update, name="section-update"),
    path("sections/<str:pk>/delete/", htmx_crud_views.section_delete, name="section-delete"),
    path("sections/<str:pk>/delete/confirm/", htmx_crud_views.section_confirm_delete, name="section-confirm-delete"),
    path("exercises/", htmx_crud_views.exercise_list, name="exercise-list"),
    path("exercises/create/", htmx_crud_views.exercise_create, name="exercise-create"),
    path("exercises/bulk-create/", views.exercise_bulk_create, name="exercise-bulk-create"),
    path("exercises/page-range-row/", views.page_range_row, name="page-range-row"),
    path("exercises/<str:pk>/", htmx_crud_views.exercise_row, name="exercise-row"),
    path("exercises/<str:pk>/detail/", views.exercise_detail, name="exercise-detail"),
    path("exercises/<str:pk>/detail/quick-log/", views.exercise_quick_log, name="exercise-quick-log"),
    path("exercises/<str:pk>/upload-notation/", views.exercise_upload_notation, name="exercise-upload-notation"),
    path("exercises/<str:pk>/edit/", htmx_crud_views.exercise_edit, name="exercise-edit"),
    path("exercises/<str:pk>/update/", htmx_crud_views.exercise_update, name="exercise-update"),
    path("exercises/<str:pk>/delete/", htmx_crud_views.exercise_delete, name="exercise-delete"),
    path("exercises/<str:pk>/delete/confirm/", htmx_crud_views.exercise_confirm_delete, name="exercise-confirm-delete"),
    path("logs/", htmx_crud_views.practice_log_list, name="log-list"),
    path("logs/create/", htmx_crud_views.practice_log_create, name="log-create"),
    path("logs/section-options/", views.section_options, name="section-options"),
    path("logs/exercise-options/", views.exercise_options, name="exercise-options"),
    path("logs/<str:pk>/", htmx_crud_views.practice_log_row, name="log-row"),
    path("logs/<str:pk>/edit/", htmx_crud_views.practice_log_edit, name="log-edit"),
    path("logs/<str:pk>/update/", htmx_crud_views.practice_log_update, name="log-update"),
    path("logs/<str:pk>/delete/", htmx_crud_views.practice_log_delete, name="log-delete"),
    path("logs/<str:pk>/delete/confirm/", htmx_crud_views.practice_log_confirm_delete, name="log-confirm-delete"),
]
