---
name: Lint

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: astral-sh/ruff-action@v4.0.0
        with:
          args: "--version"
          version-file: "pyproject.toml"

      - run: ruff check --fix

      - run: ruff format

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version-file: pyproject.toml

      - uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras --all-groups
        env:
          UV_PROJECT_ENVIRONMENT: ${{ env.pythonLocation }}

      - name: Type check
        uses: jakebailey/pyright-action@v3.0.2

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color

  dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
